name: Check Markdown links

on: 
  push:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Debug - List files
      run: |
        pwd
        ls -la
        find . -name "*.md" -type f
        
    - name: Create link checker config
      run: |
        cat > .github/markdown-link-check-config.json << 'EOF'
        {
          "ignorePatterns": [
            {
              "pattern": "^http://localhost"
            },
            {
              "pattern": "^#"
            },
            {
              "pattern": "^mailto:"
            },
            {
              "pattern": "^https://www.linkedin.com"
            }
          ],
          "replacementPatterns": [],
          "timeout": "30s",
          "retryOn429": true,
          "retryCount": 5,
          "fallbackRetryDelay": "30s",
          "aliveStatusCodes": [200, 206, 403, 429, 0]
        }
        EOF
        
    - name: Check Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'no'
        use-verbose-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
        folder-path: '.'
        max-depth: 2
