name: Check Markdown links

on: 
  push:
    paths:
      - '**/*.md'
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        folder-path: '.'
        config-file: '.github/markdown-link-check-config.json'
        check-modified-files-only: 'no'
        base-branch: 'main'
